---
title: "descriptive and exploratory analyses"
author: "baf44"
date: "2023-08-02"
output: html_document
editor_options: 
  chunk_output_type: console
---

## Set up

```{r load packages }
# load packages
library(data.table)
library(boot) 
library(table1)
library(ggplot2)
library(dplyr)
library(haven)
library(reshape2)
library(corrplot)

```

```{r load generated datasets, include=FALSE}

#source("code/feis_portionsize.R")
source("code/gen_fmri_index.R") # this sources setup_data.R, feis_portionsize.R, gen_fmricovtable.R
```

```{r change -999 to NA , include=FALSE}

# Replace all occurrences of -999 with NA
fmri_covariates[fmri_covariates == -999] <- NA

```


## Determine sample

```{r fmri sample, include=TRUE}

# combine subset dfs (generated by gen_fmri_index.R) into list
subset_analyses_lists <- list(subset_lin_app, subset_quad_app, subset_fr_app, subset_sr_app, subset_lin_cer, subset_quad_cer, subset_fr_cer, subset_sr_cer)

# Extract the "sub" column from all dataframes and combine into a single vector
fmri_subs_included <- unique(unlist(lapply(subset_analyses_lists, function(df) df$sub)))

# count number of subjects included in any fmri analysis
length(fmri_subs_included)

```


```{r count n per fmri analysis, include=TRUE}

# check number of subjects in subset dataframes (generated by gen_fmri_index.R)
nrow(subset_lin_app)
nrow(subset_quad_app)
nrow(subset_fr_app)
nrow(subset_sr_app)
nrow(subset_lin_cer)
nrow(subset_quad_cer)
nrow(subset_fr_cer)
nrow(subset_sr_cer)
```

## Subset for analyses


```{r subset based on sample, include=TRUE}

# Subset fmri_covariates based on values in fmri_subs_included
subset_fmri_covariates <- fmri_covariates[fmri_covariates$sub %in% fmri_subs_included, ]

# Subset intake_long based on values in fmri_subs_included
intake_long$sub <- sprintf("%03d", intake_long$sub) # pad with zeros
subset_intake_long <- intake_long[intake_long$sub %in% fmri_subs_included, ]

# Subset [demographic vars] based on values in fmri_subs_included

```

```{r subset based on variables, include=TRUE}

# select behavioral variables for descriptives and correlations
beh_vars <- subset(subset_fmri_covariates, select=c(l_grams_ps_lin, l_kcal_ps_lin, q_grams_ps_quad, q_kcal_ps_quad, g_vertex, kcal_vertex, cebq_fr, cebq_sr))

# reorder columns 
new_column_order <- c("l_grams_ps_lin", 
                      "l_kcal_ps_lin",
                      "q_grams_ps_quad",
                      "q_kcal_ps_quad",
                      "g_vertex",
                      "kcal_vertex",
                      "cebq_fr",
                      "cebq_sr") 

beh_vars <- beh_vars[, new_column_order] # Reorder 

```


## Demographic analyses
```{r table: demographics, include=TRUE}
```

## Behavioral analyses

Descriptive statistics for meal variables by portion size 

```{r table: meal intake descriptives, include=TRUE}

# assign labels for table1()
label(subset_intake_long$grams) <- "Total intake, grams"
label(subset_intake_long$kcal) <- "Total intake, kcal"
label(subset_intake_long$preFF) <- "Pre-meal fullness"
label(subset_intake_long$avg_vas) <- "Average liking"

# generate table
table1(~ grams + kcal + avg_vas + preFF | PortionSize, data=subset_intake_long, overall=F)

```

Descriptive statistics for linear and quadratic FEIS slopes, verticies, and CEBQ variables

```{r table: eating behavior descriptives, include=TRUE}

# only include ones that can be interpreted? 

# assign labels for table1()
label(beh_vars$l_grams_ps_lin) <- "linear slope, g"
label(beh_vars$l_kcal_ps_lin) <- "linear slope, kcal"
label(beh_vars$q_grams_ps_quad) <- "quadratic slope, g"
label(beh_vars$q_kcal_ps_quad) <- "quadratic slope, kcal"
label(beh_vars$g_vertex) <- "vertex, g"
label(beh_vars$kcal_vertex) <- "vertex, kcal"
label(beh_vars$cebq_fr) <- "food responsiveness"
label(beh_vars$cebq_sr) <- "satiety responsiveness"

# generate table
table1(~ l_grams_ps_lin + l_kcal_ps_lin + q_grams_ps_quad + q_kcal_ps_quad + 
         g_vertex + kcal_vertex + cebq_fr + cebq_sr, data=beh_vars, overall=T)

```

Exploratory correlations between linear and quadratic FEIS slopes, verticies, and CEBQ variables

```{r eating behavior associations, include=TRUE}

# generate correlation matrix between behavioral variables
cor_matrix <- cor(beh_vars, use = "pairwise.complete.obs")

# Define labels
varnames <- c("linear slope, g", 
              "linear slope, kcal", 
              "quadratic slope, g", 
              "quadratic slope, kcal", 
              "vertex, g", 
              "vertex, kcal",
              "food responsiveness",
              "satiety responsiveness")

# Assign column and row labels
colnames(cor_matrix) <- varnames
rownames(cor_matrix) <- varnames

# plot matrix
corrplot(cor_matrix, method = "circle", type = "upper", 
         tl.col = "black", # make font black
         tl.cex = 0.8) # make font smaller

```

