---
title: "assess_distributions"
author: "baf44"
date: "2023-09-27"
output: html_document
---

Code to assess distributions of eating behavior variables and determine subjects who are outliers on vertex variable 

## Set up

```{r load packages }
# load packages
library(data.table)
library(table1)
library(ggplot2)
library(corrplot)
library(tidyr) # to use "gather()"
library(Hmisc) # to plot all histograms in a dataframe
library(RcmdrMisc)
library(matrixcalc)
library(psych)
library(EnvStats) # for rosnerTest()
```

```{r load generated datasets, include=FALSE}

source("code/gen_fmri_index.R") # this sources setup_data.R, feis_portionsize.R, gen_fmricovtable.R, determine_analysis_sample.R

```

```{r change -999 to NA , include=FALSE}

# Replace all occurrences of -999 with NA
fmri_covariates[fmri_covariates == -999] <- NA

```

## Histograms

```{r histogram: meal intake, include=TRUE}

# total grams consumed, overlap by by portion size
ggplot(intake_long_analyze, aes(x=grams, fill = as.factor(PortionSize)))+
   geom_histogram( color='#e9ecef', alpha=1, position='identity')

# total kcal consumed, overlap by portion size
ggplot(intake_long_analyze, aes(x=kcal, fill = as.factor(PortionSize)))+
   geom_histogram( color='#e9ecef', alpha=1, position='identity')

# total grams consumed, facet by portion size
ggplot(intake_long_analyze, aes(grams)) + geom_histogram(bins = 15) + facet_wrap(~PortionSize)

# total kcal consumed, facet by portion size
ggplot(intake_long_analyze, aes(kcal)) + geom_histogram(bins = 15) + facet_wrap(~PortionSize)
```


```{r histograms: eating behaviors, include=TRUE}

plot(hist(beh_vars$l_grams_ps_lin), main = "Linear PSE (grams)", cex.main = 2, cex.lab = 1.2)
plot(hist(beh_vars$l_kcal_ps_lin), main = "Linear PSE (kcal)", cex.main = 2, cex.lab = 1.2)
plot(hist(beh_vars$q_grams_ps_quad), main = "Quadratic PSE (grams)", cex.main = 2, cex.lab = 1.2)
plot(hist(beh_vars$q_kcal_ps_quad), main = "Quadratic PSE (kcal)", cex.main = 2, cex.lab = 1.2)
plot(hist(beh_vars$g_vertex), main = "Vertex (grams)", cex.main = 2, cex.lab = 1.2) # do analyses with and without outlier?
plot(hist(beh_vars$kcal_vertex), main = "Vertex (kcal)", cex.main = 2, cex.lab = 1.2) # do analyses with and without outlier?
plot(hist(beh_vars$cebq_fr), main = "Food responsiveness", cex.main = 2, cex.lab = 1.2) 
plot(hist(beh_vars$cebq_sr), main = "Satiety responsiveness", cex.main = 2, cex.lab = 1.2)

hist(beh_vars$kcal_vertex, breaks = 100) # visualize histograms with more breaks
hist(beh_vars$g_vertex, breaks = 100) # visualize histograms with more breaks

# test normality using Kolmogorov Smirnov -- p < 0.05 indicates significant difference from normal distribution
ks.test(beh_vars$l_grams_ps_lin, "pnorm", mean=mean(beh_vars$l_grams_ps_lin, na.rm = TRUE), sd=sd(beh_vars$l_grams_ps_lin, na.rm = TRUE))
ks.test(beh_vars$l_kcal_ps_lin, "pnorm", mean=mean(beh_vars$l_kcal_ps_lin, na.rm = TRUE), sd=sd(beh_vars$l_kcal_ps_lin, na.rm = TRUE))
ks.test(beh_vars$q_grams_ps_quad, "pnorm", mean=mean(beh_vars$q_grams_ps_quad, na.rm = TRUE), sd=sd(beh_vars$q_grams_ps_quad, na.rm = TRUE))
ks.test(beh_vars$q_kcal_ps_quad, "pnorm", mean=mean(beh_vars$q_kcal_ps_quad, na.rm = TRUE), sd=sd(beh_vars$q_kcal_ps_quad, na.rm = TRUE))
ks.test(beh_vars$g_vertex, "pnorm", mean=mean(beh_vars$g_vertex, na.rm = TRUE), sd=sd(beh_vars$g_vertex, na.rm = TRUE))
ks.test(beh_vars$kcal_vertex, "pnorm", mean=mean(beh_vars$kcal_vertex, na.rm = TRUE), sd=sd(beh_vars$kcal_vertex, na.rm = TRUE))
ks.test(beh_vars$cebq_fr, "pnorm", mean=mean(beh_vars$cebq_fr, na.rm = TRUE), sd=sd(beh_vars$cebq_fr, na.rm = TRUE))
ks.test(beh_vars$cebq_sr, "pnorm", mean=mean(beh_vars$cebq_sr, na.rm = TRUE), sd=sd(beh_vars$cebq_sr, na.rm = TRUE))


```

## Vertex outliers

```{r determine vertex outliers, include=TRUE}

# Examine qqplot with qqline to get k outliers
qqnorm(subset_fmri_covariates$g_vertex, pch = 1, frame = FALSE)
qqline(subset_fmri_covariates$g_vertex) # k = 5 outliers (>1 sample quantile)

qqnorm(subset_fmri_covariates$kcal_vertex, pch = 1, frame = FALSE) #3 outliers 
qqline(beh_vars$kcal_vertex) # k = 3 outliers 

## use k outliers for Rosner outlier detection 
g_vertex_rosner <- rosnerTest(subset_fmri_covariates$g_vertex,
  k = 5
)

kcal_vertex_rosner <- rosnerTest(subset_fmri_covariates$kcal_vertex,
  k = 3
)

# save results of rosner test to dataframe -- Obs.Num indicates parID
g_vertex_rosner_df <- as.data.frame(g_vertex_rosner$all.stats)
kcal_vertex_rosner_df <- as.data.frame(kcal_vertex_rosner$all.stats)

# extract Obs.Num where Outlier = TRUE
g_vertex_rosner_outliers_obsnum <- g_vertex_rosner_df[g_vertex_rosner_df$Outlier == 'TRUE',]$Obs.Num
kcal_vertex_rosner_outliers_obsnum <- kcal_vertex_rosner_df[kcal_vertex_rosner_df$Outlier == 'TRUE',]$Obs.Num

# get sub values for Outlier Obs.Nums
g_vertex_rosner_outliers_parnum <- subset_fmri_covariates[c(g_vertex_rosner_outliers),]$sub
kcal_vertex_rosner_outliers_parnum <- subset_fmri_covariates[c(kcal_vertex_rosner_outliers_obsnum),]$sub

# make dataframes without outliers
g_vertex_no_outliers <- subset_fmri_covariates[ ! subset_fmri_covariates$sub %in% g_vertex_rosner_outliers_parnum, ]
kcal_vertex_no_outliers <- subset_fmri_covariates[ ! subset_fmri_covariates$sub %in% kcal_vertex_rosner_outliers_parnum, ]

# assess distributions without outliers
plot(hist(g_vertex_no_outliers$g_vertex), main = "Vertex (grams)", cex.main = 2, cex.lab = 1.2)
plot(hist(kcal_vertex_no_outliers$kcal_vertex), main = "Vertex (kcal)", cex.main = 2, cex.lab = 1.2)

# test distribution without outliers
ks.test(g_vertex_no_outliers$g_vertex, "pnorm", mean=mean(g_vertex_no_outliers$g_vertex, na.rm = TRUE), sd=sd(g_vertex_no_outliers$g_vertex, na.rm = TRUE))
ks.test(kcal_vertex_no_outliers$kcal_vertex, "pnorm", mean=mean(kcal_vertex_no_outliers$kcal_vertex, na.rm = TRUE), sd=sd(kcal_vertex_no_outliers$kcal_vertex, na.rm = TRUE))

```
